name: boiling_flow
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - setuptools
  # Core dependencies
  - numpy
  - scipy
  # Docs dependencies
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-book-theme>=1.0.1
  - sphinx-design
  - sphinx-copybutton
  # Demo dependencies
  - matplotlib
  - Pillow>=9.1
  - pip:
      - -e .